"""update Teachers
Revision ID: b2e8fba9f45f
Revises: f67cb1820876
Create Date: 2023-02-24 22:03:44.264734
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e8fba9f45f'
down_revision = 'f67cb1820876'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###