"""Add Avatar Field
Revision ID: 63b5fed793b6
Revises: 91d36ea07222
Create Date: 2023-04-17 13:18:22.702020
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b5fed793b6'
down_revision = '91d36ea07222'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###