"""Add confirm field at User Model
Revision ID: 91d36ea07222
Revises: d6ec0d8727cd
Create Date: 2023-04-12 20:13:46.154137
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d36ea07222'
down_revision = 'd6ec0d8727cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###